/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as MemoriesRouteImport } from './routes/memories'
import { Route as MemorySearchRouteImport } from './routes/memory-search'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as OrganismRouteImport } from './routes/organism'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesRoute = MemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => rootRouteImport,
} as any)
const MemorySearchRoute = MemorySearchRouteImport.update({
  id: '/memory-search',
  path: '/memory-search',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganismRoute = OrganismRouteImport.update({
  id: '/organism',
  path: '/organism',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/integrations': typeof IntegrationsRoute
  '/memories': typeof MemoriesRoute
  '/memory-search': typeof MemorySearchRoute
  '/ops': typeof OpsRoute
  '/organism': typeof OrganismRoute
  '/workspace': typeof WorkspaceRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/integrations': typeof IntegrationsRoute
  '/memories': typeof MemoriesRoute
  '/memory-search': typeof MemorySearchRoute
  '/ops': typeof OpsRoute
  '/organism': typeof OrganismRoute
  '/workspace': typeof WorkspaceRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/integrations': typeof IntegrationsRoute
  '/memories': typeof MemoriesRoute
  '/memory-search': typeof MemorySearchRoute
  '/ops': typeof OpsRoute
  '/organism': typeof OrganismRoute
  '/workspace': typeof WorkspaceRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/integrations'
    | '/memories'
    | '/memory-search'
    | '/ops'
    | '/organism'
    | '/workspace'
    | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/integrations'
    | '/memories'
    | '/memory-search'
    | '/ops'
    | '/organism'
    | '/workspace'
    | '/api/chat'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/integrations'
    | '/memories'
    | '/memory-search'
    | '/ops'
    | '/organism'
    | '/workspace'
    | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  IntegrationsRoute: typeof IntegrationsRoute
  MemoriesRoute: typeof MemoriesRoute
  MemorySearchRoute: typeof MemorySearchRoute
  OpsRoute: typeof OpsRoute
  OrganismRoute: typeof OrganismRoute
  WorkspaceRoute: typeof WorkspaceRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories': {
      id: '/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof MemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory-search': {
      id: '/memory-search'
      path: '/memory-search'
      fullPath: '/memory-search'
      preLoaderRoute: typeof MemorySearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organism': {
      id: '/organism'
      path: '/organism'
      fullPath: '/organism'
      preLoaderRoute: typeof OrganismRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  IntegrationsRoute: IntegrationsRoute,
  MemoriesRoute: MemoriesRoute,
  MemorySearchRoute: MemorySearchRoute,
  OpsRoute: OpsRoute,
  OrganismRoute: OrganismRoute,
  WorkspaceRoute: WorkspaceRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
