"""Guest clock startup guard for the governed F2 boundary.

Once P2 runs inside the guest, ``delivery_timestamp``
(``runtime_v2/services/f2_replay.py:342``, ``time.time()``) is generated by the
GUEST clock, while ``freeze_timestamp``
(``runtime_v2/services/f2_freeze.py:111``) is generated by the HOST clock. With
Hyper-V Time Synchronization disabled these are different clock domains, so the
guest clock must be plausibility-checked against a host-recorded reference that
travels in the immutable input bundle -- WITHOUT the guest contacting the host for
the time (that would add a network dependency and defeat the check).

This module is pure and deterministic (no clock read, no I/O) so it is unit
testable without a VM. The caller supplies the two UTC instants and the tolerance.
It does not alter F0/F1 delivery-timestamp semantics (the 2025-01-01 floor lives
in ``qwen_train/f2_protocol.py`` and is unchanged).
"""

from __future__ import annotations

import json
from datetime import datetime, timezone

#: Default tolerated absolute skew between the guest clock and the host reference.
#: Rationale: the guest boot clock is seeded from the host RTC at VM start; over the
#: bounded life of one arm (minutes) a free-running HPET/RTC drift is well under a
#: few seconds. 120 s absorbs an NTP-less boot resume while still catching a
#: day/year-scale skew or a clock set to the wrong epoch.
DEFAULT_CLOCK_TOLERANCE_S = 120.0

STATUS_OK = "OK"
STATUS_FAIL = "FAIL"

REASON_OUTSIDE = "GUEST_CLOCK_OUTSIDE_ALLOWED_WINDOW"
REASON_MALFORMED_REFERENCE = "HOST_REFERENCE_MALFORMED"
REASON_MALFORMED_GUEST = "GUEST_TIMESTAMP_MALFORMED"


def _parse_utc(value: object) -> datetime | None:
    """Parse an epoch-seconds number or an ISO-8601 UTC string to aware UTC.

    Returns None on any malformed input (fail closed; never substitutes now()).
    """
    if isinstance(value, bool) or value is None:
        return None
    if isinstance(value, (int, float)):
        try:
            return datetime.fromtimestamp(float(value), tz=timezone.utc)
        except (OverflowError, OSError, ValueError):
            return None
    if isinstance(value, str):
        text = value.strip()
        if not text:
            return None
        try:
            dt = datetime.fromisoformat(text.replace("Z", "+00:00"))
        except ValueError:
            return None
        if dt.tzinfo is None:
            return None
        return dt.astimezone(timezone.utc)
    return None


def evaluate_clock(
    *,
    guest_utc: object,
    host_reference_utc: object,
    tolerance_seconds: float = DEFAULT_CLOCK_TOLERANCE_S,
) -> dict:
    """Evaluate guest clock plausibility; return a deterministic result dict.

    ``status`` is ``OK`` iff both instants parse and ``|skew| <= tolerance``.
    Otherwise ``FAIL`` with an unambiguous ``reason``. Never reads the clock.
    """
    guest = _parse_utc(guest_utc)
    reference = _parse_utc(host_reference_utc)

    result = {
        "guest_utc": guest.isoformat() if guest else None,
        "host_reference_utc": reference.isoformat() if reference else None,
        "clock_skew_seconds": None,
        "clock_tolerance_seconds": float(tolerance_seconds),
        "clock_status": STATUS_OK,
        "reason": "",
    }
    if reference is None:
        result["clock_status"] = STATUS_FAIL
        result["reason"] = REASON_MALFORMED_REFERENCE
        return result
    if guest is None:
        result["clock_status"] = STATUS_FAIL
        result["reason"] = REASON_MALFORMED_GUEST
        return result

    skew = (guest - reference).total_seconds()
    result["clock_skew_seconds"] = skew
    if abs(skew) > float(tolerance_seconds):
        result["clock_status"] = STATUS_FAIL
        result["reason"] = REASON_OUTSIDE
    return result


def dumps(result: dict) -> str:
    """Deterministic JSON serialization (sorted keys, fixed separators)."""
    return json.dumps(result, sort_keys=True, separators=(",", ":"))
