from typing import Protocol, Optional
from ..contracts.runtime import RunContext, RuntimeEvent
from ..state.stream_state import StreamState
from ..state.task import Task


class Storage(Protocol):
    def save_context(self, context: RunContext) -> None: ...
    def save_state(self, state: StreamState) -> None: ...
    def load_state(self, run_id: str) -> Optional[StreamState]: ...
    def save_task(self, task: Task) -> None: ...
    def append_event(self, event: RuntimeEvent) -> None: ...
